#!/bin/bash

Mem=`free -m | awk '/Mem:/{print $2}'`
Swap=`free -m | awk '/Swap:/{print $2}'`

if [ $Mem -le 640 ]; then
  Mem_level=512M
  Memory_limit=64
  THREAD=1
elif [ $Mem -gt 640 -a $Mem -le 1280 ]; then
  Mem_level=1G
  Memory_limit=128
elif [ $Mem -gt 1280 -a $Mem -le 2500 ]; then
  Mem_level=2G
  Memory_limit=192
elif [ $Mem -gt 2500 -a $Mem -le 3500 ]; then
  Mem_level=3G
  Memory_limit=256
elif [ $Mem -gt 3500 -a $Mem -le 4500 ]; then
  Mem_level=4G
  Memory_limit=320
elif [ $Mem -gt 4500 -a $Mem -le 8000 ]; then
  Mem_level=6G
  Memory_limit=384
elif [ $Mem -gt 8000 ]; then
  Mem_level=8G
  Memory_limit=448
fi

Make-swapfile() {
  dd if=/dev/zero of=/swapfile count=$COUNT bs=1M
  mkswap /swapfile
  swapon /swapfile
  chmod 600 /swapfile
  [ -z "`grep swapfile /etc/fstab`" ] && echo '/swapfile    swap    swap    defaults    0 0' >> /etc/fstab
}

function Colorset() {
  #颜色配置
  echo=echo
  for cmd in echo /bin/echo; do
    $cmd >/dev/null 2>&1 || continue
    if ! $cmd -e "" | grep -qE '^-e'; then
      echo=$cmd
      break
    fi
  done
  CSI=$($echo -e "\033[")
  CEND="${CSI}0m"
  CDGREEN="${CSI}32m"
  CRED="${CSI}1;31m"
  CGREEN="${CSI}1;32m"
  CYELLOW="${CSI}1;33m"
  CBLUE="${CSI}1;34m"
  CMAGENTA="${CSI}1;35m"
  CCYAN="${CSI}1;36m"
  CSUCCESS="$CDGREEN"
  CFAILURE="$CRED"
  CQUESTION="$CMAGENTA"
  CWARNING="$CYELLOW"
  CMSG="$CCYAN"
}

function Logprefix() {
  #输出log
  echo -n ${CGREEN}'CraftYun >> '
}

function Checksystem() {
  cd
  Logprefix;echo ${CMSG}'[Info]检查系统'${CEND}
  #检查系统
  if [[ $(id -u) != '0' ]]; then
    Logprefix;echo ${CWARNING}'[Error]请使用root用户安装!'${CEND}
    exit
  fi

  if grep -Eqii "CentOS" /etc/issue || grep -Eq "CentOS" /etc/*-release; then
    DISTRO='CentOS'
  else
    DISTRO='unknow'
  fi

  if [[ ${DISTRO} == 'unknow' ]]; then
    Logprefix;echo ${CWARNING}'[Error]请使用Centos系统安装!'${CEND}
    exit
  fi

  if grep -Eqi "release 5." /etc/redhat-release; then
      RHEL_Version='5'
  elif grep -Eqi "release 6." /etc/redhat-release; then
      RHEL_Version='6'
  elif grep -Eqi "release 7." /etc/redhat-release; then
      RHEL_Version='7'
  fi

  if [[ `getconf WORD_BIT` = '32' && `getconf LONG_BIT` = '64' ]] ; then
      OS_Bit='64'
  else
      OS_Bit='32'
  fi
}

function Coloseselinux() {
  #关闭selinux
  Logprefix;echo ${CMSG}'[Info]关闭Selinux'${CEND}
  [ -s /etc/selinux/config ] && sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config
	setenforce 0 >/dev/null 2>&1
}

function Yumupdate() {
  #升级系统软件
  Logprefix;echo ${CMSG}'[Info]升级系统软件,可能需要花费较长时间，请耐心等待'${CEND}
  yum -y update
}

function Installbasesoftware() {
  #安装基础软件
  Logprefix;echo ${CMSG}'[Info]安装基础软件'${CEND}
  Logprefix;echo ${CMSG}'[Info]安装epel源'${CEND}
  yum -y install epel-release
  rm -rf /etc/yum.repos.d/CentOS-Epel.repo
  Logprefix;echo ${CMSG}'[Info]安装wget'${CEND}
  yum -y install wget
  Logprefix;echo ${CMSG}'[Info]安装zip unzip'${CEND}
  yum -y install unzip zip
  # Logprefix;echo ${CMSG}'[Info]安装Development Tools'${CEND}
  # yum -y groupinstall "Development Tools"
  yum -y install yum-utils sed
}

function Askuser() {
  Logprefix;echo ${CMSG}'[Info]提示:按下回车键开始，或使用CTRL+C退出'${CEND}
  read
  Logprefix;echo ${CMSG}'[Info]创建swap区,可能需要花费较长时间，请耐心等待'${CEND}
  # add swapfile
  if [ "$Swap" == '0' ]; then
    if [ $Mem -le 1024 ]; then
      COUNT=512
      Make-swapfile
    elif [ $Mem -gt 1024 ]; then
      COUNT=2048
      Make-swapfile
    fi
  fi
  InstallKernel
  Kernel_Optimize
  InstallBBR
}

function Kernel_Optimize() {
  Logprefix;echo ${CMSG}'[Info]优化内核参数'${CEND}
  echo '# Generated by the BBR_Install script
net.ipv4.tcp_fastopen = 3' > /etc/sysctl.conf
}

function InstallKernel() {
  Coloseselinux
  Installbasesoftware
  Yumupdate
  # 安装内核
  Logprefix;echo ${CMSG}'[Info]安装kernel'${CEND}
  rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org

  if grep -Eqi "release 5." /etc/redhat-release; then
	  Logprefix;echo ${CWARNING}'[Error]请使用Centos6或7安装!'${CEND}
	  exit
  elif grep -Eqi "release 6." /etc/redhat-release; then
      rpm -Uvh 'http://www.elrepo.org/elrepo-release-6-8.el6.elrepo.noarch.rpm'
  elif grep -Eqi "release 7." /etc/redhat-release; then
      rpm -Uvh 'http://www.elrepo.org/elrepo-release-7.0-3.el7.elrepo.noarch.rpm'
  fi
  
  yum-config-manager --enable elrepo-kernel
  
  # 安装内核
  yum -y remove kernel-headers
  yum -y --enablerepo=elrepo-kernel install kernel-ml
  
  sed -i 's%DEFAULTKERNEL=kernel%DEFAULTKERNEL=kernel-ml%' /etc/sysconfig/kernel
  
  # 安装完后再次更新
  yum -y update
  
  # 设置启动顺序
  grub2-set-default 0
}

function InstallBBR() {
  echo "net.core.default_qdisc = fq" >> /etc/sysctl.conf
  echo "net.ipv4.tcp_congestion_control = bbr" >> /etc/sysctl.conf
  Logprefix;echo ${CYELLOW}'[Warning]对内核参数文件(/etc/sysctl.conf)加锁中，防止其他脚本修改，解除请运行[chattr -i /etc/sysctl.conf]'${CEND}
  chattr +i /etc/sysctl.conf
  Logprefix;echo ${CMAGENTA}'[Success]安装完成，请手动重启系统'${CEND}
}

Colorset
Checksystem

#安装开始
Askuser
